2024-05-02 14:08:37,593 INFO    StreamThr :43160 [internal.py:wandb_internal():86] W&B internal server running at pid: 43160, started at: 2024-05-02 14:08:37.593310
2024-05-02 14:08:37,601 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: status
2024-05-02 14:08:37,602 INFO    WriterThread:43160 [datastore.py:open_for_write():87] open: /home/radoslavralev/Documents/Thesis/gfn-diffusion/energy_sampling/wandb/run-20240502_140837-efxxdwgg/run-efxxdwgg.wandb
2024-05-02 14:08:37,602 DEBUG   SenderThread:43160 [sender.py:send():379] send: header
2024-05-02 14:08:37,631 DEBUG   SenderThread:43160 [sender.py:send():379] send: run
2024-05-02 14:08:42,632 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: keepalive
2024-05-02 14:08:47,634 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: keepalive
2024-05-02 14:08:52,635 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: keepalive
2024-05-02 14:08:57,636 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: keepalive
2024-05-02 14:09:02,638 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: keepalive
2024-05-02 14:09:07,639 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: keepalive
2024-05-02 14:09:12,640 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: keepalive
2024-05-02 14:09:17,642 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: keepalive
2024-05-02 14:09:22,643 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: keepalive
2024-05-02 14:09:27,645 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: keepalive
2024-05-02 14:09:32,646 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: keepalive
2024-05-02 14:09:37,648 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: keepalive
2024-05-02 14:09:41,517 INFO    SenderThread:43160 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/site-packages/urllib3/connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/radoslavralev/miniconda3/envs/gfn-diffusion/lib/python3.8/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=20)
2024-05-02 14:09:42,650 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: keepalive
2024-05-02 14:09:47,651 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: keepalive
2024-05-02 14:09:52,653 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: keepalive
2024-05-02 14:09:57,655 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: keepalive
2024-05-02 14:10:02,656 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: keepalive
2024-05-02 14:10:07,657 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: cancel
2024-05-02 14:10:07,657 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: cancel
2024-05-02 14:10:07,658 DEBUG   SenderThread:43160 [sender.py:send():388] Record cancelled: run
2024-05-02 14:10:07,658 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 14:10:08,404 DEBUG   HandlerThread:43160 [handler.py:handle_request():146] handle_request: shutdown
2024-05-02 14:10:08,404 INFO    HandlerThread:43160 [handler.py:finish():866] shutting down handler
2024-05-02 14:10:08,658 INFO    SenderThread:43160 [sender.py:finish():1546] shutting down sender
2024-05-02 14:10:08,658 INFO    WriterThread:43160 [datastore.py:close():296] close: /home/radoslavralev/Documents/Thesis/gfn-diffusion/energy_sampling/wandb/run-20240502_140837-efxxdwgg/run-efxxdwgg.wandb
